---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/25 14:24
---

if(redis.call("get",KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call("del",KEYS[1])
end
return 0